data_config:
  cache_img_path: null
  cache_workers: 0
  data_pipeline_fw: torch_dataset
  delete_cache_imgs_after_training: true
  parallel_caching: true
  preprocessing:
    crop_padding: null
    crop_size: null
    ensure_grayscale: false
    ensure_rgb: true
    max_height: 138
    max_width: 468
    min_crop_size: 100
    scale: 1.0
  provider: LabelsReader
  skeletons:
  - edges:
    - destination:
        name: head1
      source:
        name: thorax1
    - destination:
        name: abdomen1
      source:
        name: thorax1
    - destination:
        name: forelegR1
      source:
        name: thorax1
    - destination:
        name: forelegL1
      source:
        name: thorax1
    - destination:
        name: midlegR1
      source:
        name: thorax1
    - destination:
        name: midlegL1
      source:
        name: thorax1
    - destination:
        name: hindlegR1
      source:
        name: thorax1
    - destination:
        name: hindlegL1
      source:
        name: thorax1
    name: Skeleton-0
    nodes:
    - name: head1
    - name: thorax1
    - name: abdomen1
    - name: forelegR1
    - name: forelegL1
    - name: midlegR1
    - name: midlegL1
    - name: hindlegR1
    - name: hindlegL1
  test_file_path: null
  train_labels_path:
  - null
  use_augmentations_train: true
  use_existing_imgs: false
  use_same_data_for_val: false
  user_instances_only: true
  val_labels_path:
  - null
  validation_fraction: 0.0
description: ''
filename: ''
model_config:
  backbone_config:
    convnext: null
    swint:
      arch: null
      convs_per_block: 2
      filters_rate: 2
      in_channels: 3
      kernel_size: 3
      max_stride: 32
      model_type: tiny
      output_stride: 4
      patch_size: 4
      pre_trained_weights: null
      stem_patch_stride: 2
      up_interpolate: true
      window_size: 7
    unet: null
  head_configs:
    bottomup: null
    centered_instance: null
    centroid: null
    multi_class_bottomup: null
    multi_class_topdown: null
    single_instance:
      confmaps:
        output_stride: 4
        part_names:
        - head1
        - thorax1
        - abdomen1
        - forelegR1
        - forelegL1
        - midlegR1
        - midlegL1
        - hindlegR1
        - hindlegL1
        sigma: 2.5
  init_weights: default
  pretrained_backbone_weights: null
  pretrained_head_weights: null
name: drosophila_swint_pt_setB_260420_145559
sleap_nn_version: 0.1.3
trainer_config:
  ckpt_dir: null
  early_stopping:
    min_delta: 1.0e-08
    patience: 20
    stop_training_on_plateau: true
  enable_progress_bar: true
  eval:
    enabled: false
    frequency: 1
    match_threshold: 50.0
    oks_scale: null
    oks_stddev: 0.025
  keep_viz: false
  lr_scheduler:
    cosine_annealing_warmup: null
    linear_warmup_linear_decay: null
    reduce_lr_on_plateau:
      cooldown: 3
      factor: 0.5
      min_lr: 1.0e-06
      patience: 20
      threshold: 1.0e-06
      threshold_mode: rel
    step_lr: null
  max_epochs: 200
  min_train_steps_per_epoch: 200
  model_ckpt:
    save_last: true
    save_top_k: 1
  online_hard_keypoint_mining:
    hard_to_easy_ratio: 2.0
    loss_scale: 5.0
    max_hard_keypoints: null
    min_hard_keypoints: 2
    online_mining: false
  optimizer:
    amsgrad: true
    lr: 0.0001
  optimizer_name: Adam
  profiler: null
  resume_ckpt_path: null
  run_name: drosophila_swint_pt_setB_260420_145559
  save_ckpt: true
  seed: 42
  train_data_loader:
    batch_size: 6
    num_workers: 2
    shuffle: true
  train_steps_per_epoch: 200
  trainer_accelerator: gpu
  trainer_device_indices: null
  trainer_devices: 1
  trainer_strategy: auto
  use_wandb: false
  val_data_loader:
    batch_size: 6
    num_workers: 2
    shuffle: false
  visualize_preds_during_training: false
  wandb:
    api_key: null
    current_run_id: null
    delete_local_logs: null
    entity: null
    group: null
    log_viz_table: false
    name: drosophila_swint_pt_setB_260420_145559
    project: null
    prv_runid: null
    save_viz_imgs_wandb: false
    viz_box_size: 5.0
    viz_boxes: false
    viz_confmap_threshold: 0.1
    viz_enabled: true
    viz_masks: false
    wandb_mode: null
  zmq:
    controller_polling_timeout: 10
    controller_port: null
    publish_port: null
